from pydantic import BaseModel

from .enums import OpenWeatherLang


class TranslationUI(BaseModel):
    TITLE: str
    TITLE_LICENSE_UNLIMITED: str
    TITLE_LICENSE_LIMITED: str
    INPUT_BOT_TOKEN: str
    INPUT_CHAT_ID: str

    SCRIPT_NAME_CURSOR_TO_COORDINATES: str
    SCRIPT_NAME_LAUNCH_PROGRAM: str
    SCRIPT_NAME_CLOSE_PROGRAM: str
    SCRIPT_NAME_OPEN_WEBSITE: str
    SCRIPT_NAME_WAIT: str
    SCRIPT_NAME_KEYBOARD_SHORTCUT: str
    SCRIPT_NAME_TYPE_TEXT: str
    SCRIPT_NAME_PRESS_MOUSE_BUTTON: str

    SCRIPT_PLACEHOLDER_CURSOR_TO_COORDINATES: str
    SCRIPT_PLACEHOLDER_LAUNCH_PROGRAM: str
    SCRIPT_PLACEHOLDER_CLOSE_PROGRAM: str
    SCRIPT_PLACEHOLDER_OPEN_WEBSITE: str
    SCRIPT_PLACEHOLDER_WAIT: str
    SCRIPT_PLACEHOLDER_KEYBOARD_SHORTCUT: str
    SCRIPT_PLACEHOLDER_TYPE_TEXT: str
    SCRIPT_PRESS_MOUSE_BUTTON_MOUSE1: str
    SCRIPT_PRESS_MOUSE_BUTTON_MOUSE2: str
    SCRIPT_PRESS_MOUSE_BUTTON_MOUSE3: str


    SCRIPT_PLACEHOLDER_TITLE: str

    BUTTON_NEW_SCRIPT: str

    CHOOSE_FILE: str

    ACTION: str

    SCRIPT_DEFALUT_NAME_PREFIX: str

    PROGRAM_PLACEHOLDER_TITLE: str
    PROGRAM_PLACEHOLDER_PATH: str
    PROGRAM_BUTTON_NEW_COMMAND: str

    SETTINGS_NAME_DATE: str
    SETTINGS_NAME_TIME: str
    SETTINGS_NAME_DOLLAR: str
    SETTINGS_NAME_EURO: str
    SETTINGS_NAME_BTC: str
    SETTINGS_NAME_VOICE_LINES: str
    SETTINGS_NAME_AUTOSTART: str
    SETTINGS_NAME_MESSAGE_AUTODELETE: str
    SETTINGS_PLACEHOLDER_MESSAGE_AUTODELETE: str
    SETTINGS_NAME_GREETING_IMAGE: str
    SETTINGS_PLACEHOLDER_GREETING_IMAGE: str
    SETTINGS_NAME_WEATHER: str
    SETTINGS_NAME_JARVIS: str
    SETTINGS_PLACEHOLDER_CITY_ID: str
    SETTINGS_PLACEHOLDER_JARVIS_LINK: str
    SETTINGS_NAME_CHATGPT_API: str
    SETTINGS_PLACEHODLER_CHATGPT_API: str

    BUTTON_LOGS: str
    BUTTON_BOT: str
    BUTTON_SCRIPTS: str
    BUTTON_PROGRAMS: str
    BUTTON_SETTINGS: str

    BUTTON_LAUNCH: str

    LICENSE_NO_LICENSE: str

    BUTTON_CHECK_LICENSE: str

    CHECK_LICENSE_PROCESSING: str
    CHECK_LICENSE_NO_LICENSE: str

    GET_LICENSE_INPUT_TG_USERNAME: str
    GET_LICENSE_PLACEHOLDER_TG_USERNAME: str
    GET_LICENSE_BUTTON_DONE: str

    START_ICON_SHOW: str
    START_ICON_CLOSE: str
    START_ICON_TITLE: str

    JARVIS_VOICE_RECOGNITION_LANGUAGE: str = "en_US"



class TranslationLogs(BaseModel):
    # TODO(danil): mb remove these debug messages in case they are not important for localization
    # DEBUG_CLEAR_MSGS_WITH_BUTTONS: str
    # DEBUG_CLEAR_MSGS_WITH_NO_REPLY: str
    # DEBUG_CLEAR_MSGS_FOR_SCRIPTS: str
    # DEBUG_CLEAR_MSGS_WITH_REPLY_AND_TIMER: str
    # DEBUG_CLEAR_MSGS_WITH_ADDITIONAL_ARG: str

    INFO_LAUNCHING: str

    INFO_SCRIPTS: str
    INFO_FOLDERS: str
    INFO_VOLUME_DOWN: str
    INFO_VOLUME_MUTE: str
    INFO_VOLUME_UP: str

    INFO_SOUND_PREV_TRACK: str
    INFO_SOUND_NEXT_TRACK: str

    INFO_VIDEO_PLAY_PAUSE: str
    INFO_VIDEO_GO_BACKWARD: str
    INFO_VIDEO_SKIP_FORWARD: str
    INFO_VIDEO_FULLSCREEN: str

    INFO_PC_LOCK_WORKSTATION: str
    INFO_PC_CLOSE_ACTIVE_WINDOW: str
    INFO_PC_CLEAR_RECYCLE_BIN: str

    INFO_POWER_CONTROL_SLEEP: str
    INFO_POWER_CONTROL_REBOOT: str
    INFO_POWER_CONTROL_SHUT_DOWN: str
    INFO_POWER_CONTROL_HIBERNATE: str
    INFO_POWER_CONTROL_SHUT_DOWN_TIMER_CANCEL: str

    INFO_DOLLAR: str
    INFO_EURO: str
    INFO_BTC: str
    INFO_WEATHER: str
    INFO_DATE: str

    INFO_DEVICE_CONTROL_TURN_OFF_MONITOR: str

    INFO_MOUSE_CONTROL_MOVE_UP: str
    INFO_MOUSE_CONTROL_MOVE_DOWN: str
    INFO_MOUSE_CONTROL_MOVE_LEFT: str
    INFO_MOUSE_CONTROL_MOVE_RIGHT: str
    INFO_MOUSE_CONTROL_MOUSE1: str
    INFO_MOUSE_CONTROL_MOUSE2: str
    INFO_PC_TASK_MANAGER: str
    INFO_MEDIA: str
    INFO_PC: str
    INFO_INFORMATION: str
    INFO_INTERNET: str
    INFO_PROGRAMS: str
    INFO_MENU: str
    INFO_VIDEO: str
    INFO_MUSIC: str
    INFO_ADMIN: str
    INFO_VIDEO_PREV_VIDEO: str
    INFO_VIDEO_NEXT_VIDEO: str
    INFO_PC_DEVICE_MANAGEMENT: str
    INFO_DEVICE_CONTROL_MOUSE: str
    INFO_DEVICE_CONTROL_KEYBOARD: str
    INFO_PC_POWER_MANAGEMENT: str
    INFO_PC_BRIGHTNESS: str

    INFO_TRIGGER_OPEN: str
    INFO_TRIGGER_SCRIPT: str
    INFO_ADMIN_CLEAR_TEMP_FOLDER: str

    INFO_JARVIS_DISABLED: str

    INFO_SENDING_START_MESSAGE_WITH_PHOTO: str
    INFO_SENDING_START_MESSAGE_PHOTO_NOT_FOUND: str
    INFO_SENDING_START_MESSAGE_ONLY_TEXT: str
    INFO_SENDING_START_MESSAGE_SUCCESS: str
    INFO_BOT_STARTUP_SUCCESS: str
    
    INFO_LICENSE_STOP: str

    INFO_WEATHER_ASK_TO_TURN_ON_AND_CITY_ID: str

    INFO_POWER_CONTROL_SHUT_DOWN_TIMER: str
    INFO_VOLUME: str
    INFO_OPEN_LINK: str
    INFO_COMMAND_FOR_JARVIS: str
    INFO_ADMIN_CHANGE_PASSWORD: str
    INFO_PC_CHANGE_WALLPAPER: str
    
    INFO_KEYBOARD_CONTROL_TYPE: str
    INFO_KEYBOARD_CONTROL_PRESS_BUTTON: str
    INFO_PC_SCREENSHOT: str
    INFO_PC_WEBCAM_SCREENSHOT: str
    INFO_BRIGHTNESS_SET: str
    INFO_CHATGPT: str
    INFO_PC_SPEC: str


    WARNING_ADMIN_NO_PERMISSIONS: str

    ERROR_BOT_STARTUP_CHECK_BOT_TOKEN: str
    ERROR_BOT_STARTUP_CHECK_CHAT_ID: str
    ERROR_BOT_STARTUP_CHECK_MESSAGE_TO_BOT: str
    ERROR_BOT_STARTUP_RESTART: str

    ERROR_USER_CANT_ACCESS_BOT: str
    ERROR_COMMAND_FAILED_ASK_CHECK_CONFIG: str
    ERROR_JARVIS_VOICE_RECOGNITION_FAILED_NO_TEXT: str
    ERROR_JARVIS_LINK_ERROR: str
    ERROR_JARVIS_VOICE_RECOGNITION_ERROR: str
    ERROR_SENDING_START_MESSAGE_FAILED: str
    ERROR_SENDING_START_MESSAGE_CHECK_BOT_TOKEN: str
    ERROR_SENDING_START_MESSAGE_CHECK_CHAT_ID: str
    ERROR_SENDING_START_MESSAGE_MESSAGE_TO_BOT: str
    ERROR_WELCOME_MESSAGE: str
    
    ERROR_PC_CHANGE_WALLPAPER_FAILED_TO_DOWNLOAD_PHOTO: str
    ERROR_BRIGHTNESS_SET: str


# class TranslationMedia(BaseModel):
#     BUTTON_VIDEO: str
#     BUTTON_MUSIC: str

# class TranslationInfo(BaseModel):
#     BUTTON_DOLLAR: str
#     BUTTON_BTC: str
#     BUTTON_EURO: str
#     BUTTON_WEATHER: str
#     BUTTON_DATE: str   


class TranslationTGBot(BaseModel):
    BUTTON_MENU: str
    BUTTON_MEDIA: str
    BUTTON_PC: str
    BUTTON_PROGRAMS: str
    BUTTON_CHATGPT: str
    BUTTON_SCRIPTS: str
    BUTTON_INTERNET: str
    BUTTON_COMMAND_FOR_JARVIS: str

    BUTTON_CHATGPT_CLOSE: str

    BUTTON_INFO: str
    BUTTON_DATE: str
    BUTTON_WEATHER: str
    BUTTON_DOLLAR: str
    BUTTON_EURO: str
    BUTTON_BTC: str
    
    BUTTON_VIDEO: str
    BUTTON_MUSIC: str

    BUTTON_VOLUME: str
    BUTTON_VOLUME_DOWN: str
    BUTTON_VOLUME_MUTE: str
    BUTTON_VOLUME_UP: str

    BUTTON_SOUND_PREV_TRACK: str
    BUTTON_SOUND_NEXT_TRACK: str
    BUTTON_SOUND_PLAY_PAUSE: str

    BUTTON_VIDEO_PLAY_PAUSE: str
    BUTTON_VIDEO_SKIP_FORWARD: str
    BUTTON_VIDEO_GO_BACKWARD: str
    BUTTON_VIDEO_PREV_VIDEO: str
    BUTTON_VIDEO_NEXT_VIDEO: str
    BUTTON_VIDEO_FULLSCREEN: str

    BUTTON_OPEN_LINK: str
    BUTTON_SPEEDTEST: str

    BUTTON_PC_SPEC: str
    BUTTON_PC_FOLDERS: str
    BUTTON_PC_LOCK_WORKSTATION: str
    BUTTON_PC_BRIGHTNESS: str
    BUTTON_PC_CLOSE_ACTIVE_WINDOW: str
    BUTTON_PC_CHANGE_WALLPAPER: str
    BUTTON_PC_TEXT_ALERT: str
    BUTTON_PC_CLEAR_RECYCLE_BIN: str
    BUTTON_PC_WEBCAM_SCREENSHOT: str
    BUTTON_PC_SCREENSHOT: str
    BUTTON_PC_POWER_MANAGEMENT: str
    BUTTON_PC_DEVICE_MANAGEMENT: str
    BUTTON_PC_TASK_MANAGER: str

    BUTTON_POWER_CONTROL_SLEEP: str
    BUTTON_POWER_CONTROL_HIBERNATE: str
    BUTTON_POWER_CONTROL_REBOOT: str
    BUTTON_POWER_CONTROL_SHUT_DOWN: str
    BUTTON_POWER_CONTROL_SHUT_DOWN_TIMER: str
    BUTTON_POWER_CONTROL_SHUT_DOWN_TIMER_CANCEL: str

    BUTTON_DEVICE_CONTROL_MOUSE: str
    BUTTON_DEVICE_CONTROL_KEYBOARD: str
    BUTTON_DEVICE_CONTROL_TURN_OFF_MONITOR: str

    BUTTON_MOUSE_CONTROL_MOUSE1: str
    BUTTON_MOUSE_CONTROL_MOUSE2: str
    BUTTON_MOUSE_CONTROL_MOVE_UP: str
    BUTTON_MOUSE_CONTROL_MOVE_DOWN: str
    BUTTON_MOUSE_CONTROL_MOVE_LEFT: str
    BUTTON_MOUSE_CONTROL_MOVE_RIGHT: str
    BUTTON_MOUSE_CONTROL_MOVE_TO_COORDINATES: str

    BUTTON_BRIGHTNESS_SET_0_PCT: str
    BUTTON_BRIGHTNESS_SET_25_PCT: str
    BUTTON_BRIGHTNESS_SET_50_PCT: str
    BUTTON_BRIGHTNESS_SET_75_PCT: str
    BUTTON_BRIGHTNESS_SET_100_PCT: str

    BUTTON_KEYBOARD_CONTROL_TYPE: str
    BUTTON_KEYBOARD_CONTROL_PRESS_BUTTON: str

    BUTTON_ADMIN: str
    BUTTON_ADMIN_CHANGE_PASSWORD: str
    BUTTON_ADMIN_CLEAR_TEMP_FOLDER: str

    BUTTON_SCRIPT_OPEN: str
    BUTTON_PROGRAM_OPEN: str

    BUTTON_FOLDER_MANAGEMENT_DESKTOP: str
    BUTTON_FOLDER_MANAGEMENT_PREV_PAGE: str
    BUTTON_FOLDER_MANAGEMENT_NEXT_PAGE: str
    BUTTON_FOLDER_MANAGEMENT_BACK_TO_DRIVES: str
    
    BUTTON_FOLDER_MANAGEMENT_RUN: str
    BUTTON_FOLDER_MANAGEMENT_DOWNLOAD: str
    BUTTON_FOLDER_MANAGEMENT_DELETE: str
    BUTTON_FOLDER_MANAGEMENT_BACK: str

    MSG_ADMIN: str
    MSG_PC: str
    MSG_DOLLAR: str
    MSG_EURO: str
    MSG_BTC: str
    MSG_DATE: str

    MSG_EXPLORER_CURRENT_PATH_AND_PAGE: str
    MSG_EXPLORER_CURRENT_PATH_AND_ASK_FOR_ACTION: str
    MSG_EXPLORER_ASK_CHOOSE_DRIVE: str
    MSG_EXPLORER_DOWNLOAD_FILE: str

    MSG_WEATHER_ASK_TO_TURN_ON_AND_CITY_ID: str

    MSG_PC_CLEAR_RECYCLE_BIN: str

    MSG_POWER_CONTROL_SHUT_DOWN_TIMER_CANCEL: str

    MSG_DEVICE_CONTROL_TURN_OFF_MONITOR: str

    MSG_VOLUME_ASK_VOLUME: str
    MSG_POWER_CONTROL_SHUT_DOWN_TIMER_ASK_TIMER: str
    MSG_OPEN_LINK_ASK_LINK: str

    MSG_JARVIS_ASK_FOR_MESSAGE: str
    MSG_ADMIN_ASK_NEW_PASSWORD: str
    MSG_PC_CHANGE_WALLPAPER_ASK_FOR_WALLPAPER: str
    MSG_KEYBOARD_CONTROL_TYPE_ASK_FOR_TEXT: str
    MSG_KEYBOARD_CONTROL_PRESS_BUTTON_ASK_FOR_BUTTON: str
    MSG_CHATGPT_ASK_FOR_MESSAGE: str
    MSG_MOUSE_CONTROL_MOVE_TO_COORDINATES_ASK_FOR_COORDINATES: str

    MSG_JARVIS_DISABLED: str
    MSG_JARVIS_VOICE_RECOGNITION_FAILED_NO_TEXT: str
    MSG_JARVIS_PASSED_TO_JARVIS_SUCCESS: str
    MSG_JARVIS_COMMAND_ERROR_CHECK_LINK: str

    MSG_DATE_WEEKDAY_MONDAY: str
    MSG_DATE_WEEKDAY_TUESDAY: str
    MSG_DATE_WEEKDAY_WEDNESDAY: str
    MSG_DATE_WEEKDAY_THURSDAY: str
    MSG_DATE_WEEKDAY_FRIDAY: str
    MSG_DATE_WEEKDAY_SATURDAY: str
    MSG_DATE_WEEKDAY_SUNDAY: str

    MSG_DATE_MONTH_JAN: str
    MSG_DATE_MONTH_FEB: str
    MSG_DATE_MONTH_MAR: str
    MSG_DATE_MONTH_APR: str
    MSG_DATE_MONTH_MAY: str
    MSG_DATE_MONTH_JUN: str
    MSG_DATE_MONTH_JUL: str
    MSG_DATE_MONTH_AUG: str
    MSG_DATE_MONTH_SEP: str
    MSG_DATE_MONTH_OCT: str
    MSG_DATE_MONTH_NOV: str
    MSG_DATE_MONTH_DEC: str

    MSG_MOUSE_CONTROL_MOVE_TO_COORDINATES_SUCCESS: str

    MSG_ADMIN_CLEAR_TEMP_FOLDER_RESULT: str

    MSG_WEATHER_RESULT: str

    MSG_WELCOME_MSG_GREETINGS: str
    MSG_WELCOME_MSG_DATE: str
    MSG_WELCOME_MSG_TIME: str
    MSG_WELCOME_MSG_DOLLAR: str
    MSG_WELCOME_MSG_EURO: str
    MSG_WELCOME_MSG_BTC: str

    MSG_WEATHER_ERROR: str

    MSG_POWER_CONTROL_SHUT_DOWN_TIMER: str
    MSG_VOLUME_SET: str
    MSG_OPEN_LINK: str
    MSG_COMMAND_FOR_JARVIS_SUCCESS: str
    MSG_COMMAND_FOR_JARVIS_ASK_FOR_JARVIS_LINK: str
    MSG_ADMIN_CHANGE_PASSWORD_RESET_SUCCESS: str
    MSG_ADMIN_CHANGE_PASSWORD_NEW_PASSWORD_SUCCESS: str
    MSG_PC_CHANGE_WALLPAPER_SUCCESS: str
    MSG_PC_CHANGE_WALLPAPER_FAILED_TO_DOWNLOAD_PHOTO: str
    MSG_KEYBOARD_CONTROL_TYPE_SUCCESS: str
    MSG_KEYBOARD_CONTROL_PRESS_BUTTON_ERROR: str
    MSG_KEYBOARD_CONTROL_PRESS_BUTTON_SUCCESS: str
    MSG_PC_WEBCAM_SCREENSHOT_NO_WEBCAM: str
    MSG_CHATGPT_GENERATING: str
    MSG_CHATGPT_RESPONSE_SUCCESS: str
    MSG_CHATGPT_RESPONSE_FAIL_TRY_AGAIN: str
    MSG_CHATGPT_RESPONSE_FAIL_ASK_RETRY: str
    MSG_PC_SPEC_CPU: str
    MSG_PC_SPEC_GPU: str
    MSG_PC_SPEC_OS_NAME: str
    MSG_PC_SPEC_OS_VERSION: str
    MSG_PC_SPEC_RAM_SYSTEM: str

    TRIGGER_OPEN: str
    TRIGGER_SCRIPT: str

    OPENWEATHERMAP_API_LANG: OpenWeatherLang

    # INFO: TranslationInfo
    # MEDIA: TranslationMedia
    

class Translation(BaseModel):
    UI: TranslationUI
    TG_BOT: TranslationTGBot
    LOGS: TranslationLogs